apiVersion: v1
kind: Service
metadata:
  name: aws-devops-service
spec:
  type: NodePort
  selector:
    app: aws-devops-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000